server:
  port: 9002

# 配置数据源信息
spring:
  datasource:
    url: jdbc:mysql://192.168.254.128:3306/mybatis
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
# 开辟驼峰匹配
mybatis:
  configuration:
    map-underscore-to-camel-case: true
# 打印mapper包中的sql语句日志
logging:
  level:
    com:
      spring:
        cache:
          mapper: debug
# 启动时打印自动配置报告
debug: true
